dna = "TATCGCTAGCTACG"
L = len(dna)
print(L)
A = dna.count("A")
T = dna.count("T")
C = dna.count("C")
G = dna.count('G')
print(T , A , G , C)
GC = (G + C)
print(GC/L * 100)
rna = dna.replace("T" , "U")
print(rna)
M = dna.replace("A" , "a")
M = M.replace("T" , "A")
M = M.replace("a" , "T")
M = M.replace("G" , "g")
M = M.replace("C" , "G")
M = M.replace("g" , "C")
print(M)
W = rna.replace("U" , "u")
W = W.replace("A" , "U")
W = W.replace("u" , "A")
W = W.replace("G" , "i")
W = W.replace("C" , "G")
W = W.replace("i" , "C")
print(W)